import "./globals.css";

export const metadata = {
  title: "AON Trello Clone",
  description: "Generated by Emmanuel Inua",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f5f6f8]">{children}</body>
    </html>
  );
}
